author: Nguyen Dinh Lam

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers, prometheus, metrics, trace
      base-path: /${spring.application.name}/actuator
  metrics:
    export:
      prometheus:
        enabled: true
