author: Nguyen Dinh Lam

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers, prometheus, metrics, trace
      base-path: /${server.servlet.context-path}
  metrics:
    export:
      prometheus:
        enabled: true
