author: Nguyen Dinh Lam

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers, prometheus, metrics, trace
  metrics:
    export:
      prometheus:
        enabled: true
