eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://localhost:8761/fashion-e-commerce-eureka-server}/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

server:
  servlet:
    context-path: /api
  port: 8001

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: "send_mail_verify:com.lamnguyen.authentication_service.event.SendMailVerifyEvent,save_user_detail:com.lamnguyen.authentication_service.event.SaveUserDetailEvent"
  application:
    name: fashion-e-commerce-authentication-service
  profiles:
    active: ${PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: ${application.database}
    url: ${spring.datasource.url}
    locations: classpath:db/migration
  jackson:
    mapper:
      sort-properties-alphabetically: false

application:
  white-list:
    - ${application.login-path}
    - /v1/register
    - /v1/logout
    - /v1/verify
    - /v1/resend-verify
    - /v1/reset-password/**
    - /v1/renew-access-token
    - /greeting

  login-path: ${LOGIN_PATH:/v1/login}
  prefix:
    role: ${PREFIX_ROLE:ROLE_}
    permission: ${PREFIX_PERMISSION:SCOPE_}
  token:
    blacklist: BLACKLIST
    access:
      key: ${ACCESS_TOKEN_KEY:ACCESS_TOKEN}
      default-token: ${ACCESS_TOKEN_DEFAULT_VALUE:default}
      expire: ${ACCESS_TOKEN_EXPIRE:1440}
      blacklist: ${application.token.blacklist}:${application.token.access.key}
    refresh:
      key: ${REFRESH_TOKEN_KEY:REFRESH_TOKEN}
      default-token: ${REFRESH_TOKEN_DEFAULT_VALUE:default}
      expire: ${REFRESH_TOKEN_EXPIRE:10080}
      blacklist: ${application.token.blacklist}:${application.token.refresh.key}
    reset-password:
      change: CHANGE_PASSWORD
      key: ${RESET_PASSWORD_TOKEN_KEY:REFRESH_TOKEN}
      default-token: ${RESET_PASSWORD_DEFAULT_VALUE:default}
      expire: ${RESET_PASSWORD_EXPIRE:60}
      blacklist: ${application.token.blacklist}:${application.token.refresh.key}

    otp:
      length: 6
      verify_account:
        key: ${OTP_VERITY_ACCOUNT:VERITY_ACCOUNT}
        expire: ${OTP_VERIFY_ACCOUNT_EXPIRE:10}
        total_try:
          key: ${application.token.otp.verify_account.key}:${application.token.otp.total_try}
          max_try: ${OTP_VERIFY_ACCOUNT_TOTAL_TRY:5}
        total_resend:
          key: ${application.token.otp.verify_account.key}:${application.token.otp.total_resend}
          max_resend: ${OTP_VERIFY_ACCOUNT_TOTAL_RESEND:5}
          expire: ${OTP_VERIFY_ACCOUNT_RESEND_EXPIRE:60}
      reset_password:
        key: ${OTP_RESET_PASSWORD:RESET_PASSWORD}
        expire: ${OTP_RESET_PASSWORD_EXPIRE:10}
        total_try:
          key: ${application.token.otp.reset_password.key}:${application.token.otp.total_try}
          max_try: ${OTP_RESET_PASSWORD_TOTAL_TRY:5}
        total_resend:
          key: ${application.token.otp.reset_password.key}:${application.token.otp.total_resend}
          max_resend: ${OTP_RESET_PASSWORD_TOTAL_RESEND:5}
          expire: ${OTP_RESET_PASSWORD_RESEND_EXPIRE:60}
      change_password:
        key: ${OTP_RESET_PASSWORD:RESET_PASSWORD}
        expire: ${OTP_RESET_PASSWORD_EXPIRE:10}
        total_try:
          key: ${application.token.otp.reset_password.key}:${application.token.otp.total_try}
          max_try: ${OTP_RESET_PASSWORD_TOTAL_TRY:5}
        total_resend:
          key: ${application.token.otp.reset_password.key}:${application.token.otp.total_resend}
          max_resend: ${OTP_RESET_PASSWORD_TOTAL_RESEND:5}
          expire: ${OTP_RESET_PASSWORD_RESEND_EXPIRE:60}
      total_try: ${OTP_TOTAL_TRY:TOTAL_TRY}
      total_resend: ${OTP_TOTAL_RESEND:TOTAL_RESEND}