author: Nguyen Dinh Lam Dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserveradmin:LamNguyen@1305@localhost:8761/fashion-e-commerce-eureka-server/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
