author: Nguyen Dinh Lam Dev

eureka:
  client:
    serviceUrl:
      defaultZone: https://${application.eureka.username}:${application.eureka.password}@eureka-server.ndlamdev.website/fashion-e-commerce-eureka-server/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-Ip-Address: ${PREFER_IP_ADDRESS:true}
    preferIpAddress: ${PREFER_IP_ADDRESS:true}
    ip-address: ${SERVICE_IP:127.0.0.1}
    hostname: ${EUREKA_CLIENT_HOSTNAME:localhost}
    metadata-map:
      grpc.port: ${grpc.server.port}
      gRPC__port: 0
