server:
  port: 8888
  servlet:
    context-path: /kimi-fashion

cors:
  allowed-origin:
    - http://localhost:5173
    - https://localhost_5173.ndlamdev.website

spring:
  application:
    name: fashion-e-commerce-api-gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 60000  # 10 giây
        response-timeout: 75s   # 15 giây
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service-whitelist
          uri: lb://FASHION-E-COMMERCE-AUTHENTICATION-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/auth/**, ${server.servlet.context-path}/api/authentication-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-blacklist
          uri: lb://FASHION-E-COMMERCE-AUTHENTICATION-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/role/**, ${server.servlet.context-path}/api/authorization/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: authentication-service-product-whitelist
          uri: lb://FASHION-E-COMMERCE-PRODUCT-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/product/**, ${server.servlet.context-path}/api/collection/**, ${server.servlet.context-path}/api/product-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-product-blacklist
          uri: lb://FASHION-E-COMMERCE-PRODUCT-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/admin/product/**, ${server.servlet.context-path}/api/admin/collection/**
          filters:
            - StripPrefix=1

        - id: authentication-service-cart-whitelist
          uri: lb://FASHION-E-COMMERCE-CART-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/cart-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-cart-backlist
          uri: lb://FASHION-E-COMMERCE-CART-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/cart/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: authentication-service-media-whitelist
          uri: lb://FASHION-E-COMMERCE-MEDIA-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/media-service/**, ${server.servlet.context-path}/api/resource/**
          filters:
            - StripPrefix=1

        - id: authentication-service-media-backlist
          uri: lb://FASHION-E-COMMERCE-MEDIA-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/media/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: authentication-service-profile-whitelist
          uri: lb://FASHION-E-COMMERCE-PROFILE-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/profile-service/**, ${server.servlet.context-path}/api/profile/**, ${server.servlet.context-path}/api/address/**
          filters:
            - StripPrefix=1

        - id: authentication-service-profile-backlist
          uri: lb://FASHION-E-COMMERCE-PROFILE-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/admin/profile/**, ${server.servlet.context-path}/api/admin/address/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: authentication-service-order-whitelist
          uri: lb://FASHION-E-COMMERCE-ORDER-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/order-service/**, ${server.servlet.context-path}/api/order/**
          filters:
            - StripPrefix=1

        - id: authentication-service-order-backlist
          uri: lb://FASHION-E-COMMERCE-ORDER-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/admin/order/**
          filters:
            - StripPrefix=1
            - name: Authentication
