spring:
  application:
    name: fashion-e-commerce-product-service

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #      properties:
  #        spring:
  #          json:
  #            trusted:
  #              packages: "send_mail_verify"
  #            type:
  #              mapping: "send_mail_verify:com.lamnguyen.notification_service.message.SendMailVerifyMessage"

  data:
    mongodb:
      uri: mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}/${spring.data.mongodb.database}
      database: ${MONGO_DATABASE:fashion-e-commerce}

server:
  servlet:
    context-path: /api
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://localhost:8761/fashion-e-commerce-eureka-server}/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

application:
  white-list:
    - /greeting