spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${application.database}
    username: "{cipher}AYBPcj+v+FMddQf490MDnxr4Mjpt9EqVm73kWraD70Asrd1QcU+OaMBehq7NvmeuaHKjkVObvJ+iG/l4BO2rc8zeqQ7+RCQEUmkq6/0IG3Gb0D5i3CStnB8SqRCbLm/LF3YsGQAG3hjITtGsbulojYO8sUa5liC40HP/bRuig5h5nSLEqV/MFBCSuxK2NERQfGC+H5y/X5ZMZHFwr4TYxieYVu2UPDWGj4P1V1biylxKVcLVxILlf55tFAS+/5EP2/Lp2SAcCcMWF1akneHgHQijazgdFod9i3MycbRqTxhgLv0/W/KMz9D8biAv104byIzWT9SnKP2Rvk3Q63O7WJjeIYIogXwkRHGO1isB6PkNDnQVBbJLiG/meuIC66nZ+NDimtZ0oVc05g9XY1WAkEnyEudx+DJ3AkLBIvBuquk2q0h1QCj76btRRKoXlJFRi0Ek1nyfhsTTHjpMwu1CIwuVdOICN07eas2LHsh2mCtcjm2xbWRcj7bWFomMiY1H944W/Q3m8a5/aPIlroRi6XhoHfldeRJS/1Ja6JiphadXiw=="
    password: "{cipher}AYAC4cyybAqCVirupMhQuIRQSFo7yTdUkhePKMgmzQ+7fD0rZ0mQ5IhzCePVmdE+374cCUfssGqPoFsNNNQCcl9M11UZY+yvJPy+3atD7ygDqOUDFtfb4q4Ih0HV5J4R0+xrsvltojSyC3xNLtICLIvqd2H+yg5WUYZwlAPJ3t0LHvIs8bIdC6mADzPjOtDUr8klgzgn7rQKysyaOogCwMPBXTTh4Ycsc1q4CQZDIV5lsv3vkS/U5pfh1feWNtVtGvyEJEKBukII2Ei0Qlll9rMscnS7aOTI385EcQRjFii8Bl+QO9NlsI+bSsvOuCKNpnI9+pdB/jV2paluq947xB+phRHj/L8YnF5ig31jkdHYzCVNz9pcZfZfwlEIVFbYqoJDDdUUEOEp8KDII1mnOX0s+wdUhmszsbds4g5b2S0yaTyikx3jojHn7LK3lGAO+zdO+fCU+UYC/RnmB9V9GejUOYo8iD+EwDjHVxx6Mj/CtC8XUEgZiEVbrilgJyqWvMlgsT2xHhct+HvTEEIRaqY7YGGdspz8Hf8AaXUSIcb9Kw=="
    driver-class-name: ${MYSQL_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari:
      auto-commit: ${MYSQL_AUT_COMMIT:on}
      maximum-pool-size: ${MYSQL_MAXIMUM_POOL_SIZE:8}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      database: ${REDIS_DATABASE:13}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:60000}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:60000}
      lettuce:
        pool:
          max-active: ${REDIS_MAX_POOL_ACTIVE:8}
          max-idle: ${REDIS_MAX_POOL_IDLE:8}
          min-idle: ${REDIS_MIN_POOL_IDLE:0}
          max-wait: ${REDIS_MAX_POOL_WAIT:-1}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "{cipher}AYBMTyiXio+0UUMNbxRlWjoilYIX61LjH1K1l5KVZKYkgXbdFdRPm+g/8qpAV5fn+DlDGilhAUcXNn+BMHRdwjkSn5cDZiicMSdUCFBe4ZM7b2VRUuYrqV/PprhPYIUElOJyijg8x7Q8DWt2AqYy3wuDU4nbM8JjfqEoy3Ax/4u733e6AXX1iIDQHcJgYbuWaHGdVS4KLMPN+NJIV55MgRLUF4EyZbzFq75sVC+aZjRU1a7hRSsOb5UOB4QbqA4vHGl0ZF4IZ3+y7uPeBu68al3tsv22kvAIou3Z9ZteZErPHi1FggPBJwmzu88ZpUl90L8az06D/BdO4dPjaUSu4GbsHRsFCcfvPI72n2XLIrMi4qE9+3JXH1VnCGJRjDLQpbCL8ega09fOeqwrK/3Y6XHsMVK+y/puo1D6GxxSDZTulACgA7pqD4X2pwGg+Dm+2PBAC5CpBKiNUfKsMnoJ89YIR6BDo7SYBDgHwy5nakPpwudaL81R7W37SHk3oMLd4sdq+uYe1BxE1v9roaaAbjudbq5jiET2qEcUizsJs2XHxoBaj9nMJs2l05SFaoCyl7hfAVRwYorbZAb9ugHqHYwuc3xN+AuqqPIwSg+sP9uCDnWy4khtPvwj8cHTEJjzG80="
            client-secret: "{cipher}AYA2JWKtLwbRMEPz/zn+pwvrY72fXAHw9Q8aVhKPcPOPyQg0t6mFbRVozcw6MKlV2dKoc8YRnrvwEy4DwlBmHeYmGODDdm/UK1h+tb+Al3JBRV5Q/QWyF0fIzMa6LcRSW+7oVW20aG0Ogd7Pvbt7BkFSp2z1Km88hW3l0d/cyrB6psNAGSiWcvpIC6xEbC9Wl9F12S28dhzBQPeGaXPKEunTvoI6xVgbVHxAoCFPOp0VWsDEznVWhepiwr9ooPOva4GYqz5u36sNxv4FGqsA36N9lGECKyLtSqh2L08s1YIGCvxhllUD5YcqZ+yH7+ZXloen2ZykSpiStU5cSlh2JicLvPMW4MeJgoFcgPLF5U9yWrJTW7lTwT7q7GetNDVRI7C6uJLTWnyJD0YopgEfHl01AssHJWpQI9VEcVD8VLLoiutckP9DJwbOzMnp1Qr3aJ+4tNbMj6r1TJXhddstEDwi3Y8HiYgtS5/uDC0MbwKuJh2zYh5vV1iK/hhZROhXdCPTuBltYGQtFVB9Om+9Yqbda4NAB/KZKYLdC+UScUxlkcVBiesU4w0hrPqf6/jDc6d15Kt5KI+GpaZOTE1yotMM"

application:
  admin:
    email: "{cipher}AYCIrfv0XWqsIi0LATDBHY9yig/pTsxhEEFWk3ohfCqEhxsc+1Z2TRsRKqQhRM5ea6HfQcAiR2l0CW4Vcaj+PnVG2Rc2HZBKFAsWVl5GZL1RHT4BiKMd1+/zLexJbXjUs1XDQl3TH9YGedRWD4qjhuWYM3ohiFlWYBIN/AGECY0GOegfVVoffjBrlzzz50CbRyFRipY/YYe8LDtcLby7JESKbdwX5xPSi7x+813w47bqAqmVDIQCNwv4hGtUrMHXZrJ69Yva7y0sZUuqlegFF8RpVW6UzEl+PNqrTPfbbpWKrlzjvRG6bPezqn5O6h/1bDHizyvaz7Yay1DE8NdrE3bykwhVffRuTjoXeAjnzVmyVrVvN1hiHj8mFKwm/xQPVogLD6GFsUJxluHhybbjMJ9j8cCJu8gtR62ErYN9bF+q75Laq7jy4HQHLXfGiQ9ayIk0rkl901/N/fSURjKrJTR3ZHlLKGz8DiD2zp62ovZRV4M1kqLhNNT7zhKYfvfHoY2i4w45mFeAgjkf1jzg3yub47ZBMge934f2fC3qVZnqGyrv+S4Y74F/AuOHN18gv+Q="
    password: "{cipher}AYCTe3+9ZjXKHCyCJDNcWeOmf263RJeghDOpopXu1fF9Moyrwsu7/eLi7aLIR+bB9rOy+u6FBJp9P9533/AHu2GB+j5SF2uiNa8Xms5uKH5Xve+e5KACKArRhM1NlPGt6Vgp5T6RHwIKyCLfB/TkbOhTpRNoMCFUZ4wIbj2O/fWk7nslNdtAQ7W1488dL70XWO+oZX4Wk/noJev0bbANgvjQ574EsLkpKlytGEt+qKZDwowRpTcy6pDsT52perAEdlGNvqR8vf38F2RPpOB07BDJOST+JaiUqK4etujWN10uaV1Fsmpbp4g4EMGuiL1qmXQ3LZ00Oo98d8M4OfHcRkNqVBMYiF+GnysLJF/vRYye7A6FWadm6rApTSfg3fP/PG5cdCcvESjhIu0hIqFAZo+gIKv8gB4yFexsIeKs3wa2Je8m1OlP/n94ccrLa8XUBMU0j+Iewn8Xpl/ra738Fr255NzNXn/Zd2fl6PyHhnOX34NnSy+wwield5NrRRW1oBpPc0iVlBDY3cATxJ0MGnL+7LUSvGzoolzrM0h/q5uX3ST+KOgC/mzzz+N2cAPAcLE="
  database: ${MYSQL_DATABASE:authentication_fashion_e_commerce}
  BCrypt-length: ${BCRYPT_LENGTH:16}
  jwt:
    iss: ${JWT_ISS:https://kimi-fashion-e-commerce.com}
    secret-key: "{cipher}AYAwK/NJIPXnS+YLr1wCQeIh94/42h9SbRfSGA1Lx8HkY9hVQ2sye5NUeU57PN2rtgT3ECPrQXFKCnGH9mdp5PrpjDcvE0uFV+v7yfHL2ENW+N1XGVF9LTEpl/LWWLKFxnPBapLwgzdEVm/7ZYEL2jDBj4i7Zzlxe0ZG/XfvnGgOnwsmU2mKpGXP8KJAr+c5aYLe1c1IibF1I+Ftgjl3FNgznyEsNW1bz8NcIL/cx2tTAneeLtQI5pHKN+aH4kU2nSXRuVNxlhAz5p+Mzvo2xWZfGyxDa/A2+FpN6EsNFBPlyrzmJDgEBIbyGgjMs1Yq9O4LhiCPbkbcbBAnhqH9/k1kVMZ5AYpNWVu2S7V8g8h8Snkdk7rmh+CHbMNvnPAKJzRiQV8xQNVpuSO82gIaf38790uFyGVe7heiaNlesm7/Ybjfph0F1daZ87fWqOWABzqifAllGQKQh3aaYwYDNQClPe/1Tydgvhnv8+rX9S3aWafd274VciKn3PDZTVgJkuCMcg+rWaCX9OPxCo2siqGEQtsQI3wNJuDB3TrdNxP1u99gNV/Ufa5QZacQrv/VuWUoY03/9bWoiYR/imN2Augk1Cy+s1m+L3kYXEncBtzudsWGc3oWmsewkprgVdLe5Dk="
    claim: ${JWT_CLAIM:payload}

logging:
  level:
    org.springframework.security: trace
