server:
  servlet:
    context-path: /api
  port: 8000


spring:
  application:
    name: fashion-e-commerce-notification-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:notify_group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "send_mail_verify"
            type:
              mapping: "send_mail_verify:com.lamnguyen.notification_service.message.SendMailVerifyMessage"
