server:
  servlet:
    context-path: /api
  port: 8001

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    topic:
      create-cart: create-cart
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
               mapping: "send_mail_verify:com.lamnguyen.authentication_service.event.SendMailVerifyEvent,save_profile:com.lamnguyen.authentication_service.event.SaveProfileUserEvent,update_avatar_user:com.lamnguyen.authentication_service.event.UpdateAvatarUserEvent,create_cart:com.lamnguyen.authentication_service.event.CreateCartEvent"
  application:
    name: fashion-e-commerce-authentication-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: ${application.database}
    url: ${spring.datasource.url}
    locations: classpath:db/migration
  jackson:
    mapper:
      sort-properties-alphabetically: false

application:
  white-list:
    - /${spring.application.name}/actuator/**
    - ${application.login-path}
    - /auth/v1/register
    - /auth/v1/logout
    - /auth/v1/verify
    - /auth/v1/resend-verify
    - /auth/v1/reset-password/**
    - /auth/v1/renew-access-token
    - /authentication-service/greeting
    - /auth/v1/google/**
    - /auth/v1/facebook/**

  login-path: ${LOGIN_PATH:/auth/v1/login}
  prefix:
    role: ${PREFIX_ROLE:ROLE_}
    permission: ${PREFIX_PERMISSION:SCOPE_}
  token:
    blacklist: BLACKLIST
    access:
      key: ${ACCESS_TOKEN_KEY:ACCESS_TOKEN}
      default-token: ${ACCESS_TOKEN_DEFAULT_VALUE:default}
      expire: ${ACCESS_TOKEN_EXPIRE:1440}
      blacklist: ${application.token.blacklist}:${application.token.access.key}
      facebook:
        key: ${application.token.blacklist}:${application.token.access.key}:FACEBOOK_
    refresh:
      key: ${REFRESH_TOKEN_KEY:REFRESH_TOKEN}
      default-token: ${REFRESH_TOKEN_DEFAULT_VALUE:default}
      expire: ${REFRESH_TOKEN_EXPIRE:10080}
      blacklist: ${application.token.blacklist}:${application.token.refresh.key}
    reset-password:
      change: CHANGE_PASSWORD
      key: ${RESET_PASSWORD_TOKEN_KEY:RESET_PASSWORD_TOKEN}
      default-token: ${RESET_PASSWORD_DEFAULT_VALUE:default}
      expire: ${RESET_PASSWORD_EXPIRE:60}
      blacklist: ${application.token.blacklist}:${application.token.reset-password.key}
    register:
      expire: ${EXPIRE_REGISTER_TOKEN:60}
      google:
        key: ${application.token.blacklist}:${REGISTER_TOKEN_USING_GOOGLE:REGISTER_TOKEN_WITH_GOOGLE:TOKEN_ID_}
      facebook:
        key: ${application.token.blacklist}:${REGISTER_TOKEN_USING_FACEBOOK:REGISTER_TOKEN_WITH_FACEBOOK:TOKEN_ID_}

    otp:
      length: 6
      verify_account:
        key: ${OTP_VERITY_ACCOUNT:VERITY_ACCOUNT}
        expire: ${OTP_VERIFY_ACCOUNT_EXPIRE:10}
        total_try:
          key: ${application.token.otp.verify_account.key}:${application.token.otp.total_try}
          max_try: ${OTP_VERIFY_ACCOUNT_TOTAL_TRY:5}
        total_resend:
          key: ${application.token.otp.verify_account.key}:${application.token.otp.total_resend}
          max_resend: ${OTP_VERIFY_ACCOUNT_TOTAL_RESEND:5}
          expire: ${OTP_VERIFY_ACCOUNT_RESEND_EXPIRE:60}
      reset_password:
        key: ${OTP_RESET_PASSWORD:RESET_PASSWORD}
        expire: ${OTP_RESET_PASSWORD_EXPIRE:10}
        total_try:
          key: ${application.token.otp.reset_password.key}:${application.token.otp.total_try}
          max_try: ${OTP_RESET_PASSWORD_TOTAL_TRY:5}
        total_resend:
          key: ${application.token.otp.reset_password.key}:${application.token.otp.total_resend}
          max_resend: ${OTP_RESET_PASSWORD_TOTAL_RESEND:5}
          expire: ${OTP_RESET_PASSWORD_RESEND_EXPIRE:60}
      change_password:
        key: ${OTP_RESET_PASSWORD:RESET_PASSWORD}
        expire: ${OTP_RESET_PASSWORD_EXPIRE:10}
        total_try:
          key: ${application.token.otp.reset_password.key}:${application.token.otp.total_try}
          max_try: ${OTP_RESET_PASSWORD_TOTAL_TRY:5}
        total_resend:
          key: ${application.token.otp.reset_password.key}:${application.token.otp.total_resend}
          max_resend: ${OTP_RESET_PASSWORD_TOTAL_RESEND:5}
          expire: ${OTP_RESET_PASSWORD_RESEND_EXPIRE:60}
      total_try: ${OTP_TOTAL_TRY:TOTAL_TRY}
      total_resend: ${OTP_TOTAL_RESEND:TOTAL_RESEND}

grpc:
  client:
    fashion-e-commerce-profile-service:
      enableKeepAlive: true
      negotiationType: plaintext
      load-balancer: round_robin
