server:
  port: 7999
  servlet:
    context-path: /kimi-fashion

cors:
  allowed-origin:
    - http://localhost:5173
    - https://localhost_5173.ndlamdev.website

management:
  endpoints:
    web:
      base-path: ${server.servlet.context-path}/api/${spring.application.name}/actuator

spring:
  application:
    name: fashion-e-commerce-api-gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 60000  # 10 giây
        response-timeout: 75s   # 15 giây
      discovery:
        locator:
          enabled: false # chế độ tự tạo route  theo dạng: http://<gateway-host>:<port>/AUTH-SERVICE/api/xxx
      routes:
        - id: authentication-service-whitelist
          uri: lb://FASHION-E-COMMERCE-AUTHENTICATION-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/auth/**, ${server.servlet.context-path}/api/authentication-service/**, ${server.servlet.context-path}/api/fashion-e-commerce-authentication-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-blacklist
          uri: lb://FASHION-E-COMMERCE-AUTHENTICATION-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/role/**, ${server.servlet.context-path}/api/authorization/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: authentication-service-product-whitelist
          uri: lb://FASHION-E-COMMERCE-PRODUCT-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/product/**, ${server.servlet.context-path}/api/collection/**, ${server.servlet.context-path}/api/product-service/**, ${server.servlet.context-path}/api/fashion-e-commerce-product-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-product-blacklist
          uri: lb://FASHION-E-COMMERCE-PRODUCT-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/admin/product/**, ${server.servlet.context-path}/api/admin/collection/**
          filters:
            - StripPrefix=1

        - id: authentication-service-cart-whitelist
          uri: lb://FASHION-E-COMMERCE-CART-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/cart-service/**, ${server.servlet.context-path}/api/fashion-e-commerce-cart-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-cart-backlist
          uri: lb://FASHION-E-COMMERCE-CART-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/cart/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: authentication-service-inventory-whitelist
          uri: lb://FASHION-E-COMMERCE-INVENTORY-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/inventory-service/**, ${server.servlet.context-path}/api/fashion-e-commerce-inventory-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-notification-whitelist
          uri: lb://FASHION-E-COMMERCE-NOTIFICATION-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/notification-service/**, ${server.servlet.context-path}/api/fashion-e-commerce-notification-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-media-whitelist
          uri: lb://FASHION-E-COMMERCE-MEDIA-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/media-service/**, ${server.servlet.context-path}/api/resource/**, ${server.servlet.context-path}/api/fashion-e-commerce-media-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-media-backlist
          uri: lb://FASHION-E-COMMERCE-MEDIA-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/media/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: authentication-service-profile-whitelist
          uri: lb://FASHION-E-COMMERCE-PROFILE-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/profile-service/**, ${server.servlet.context-path}/api/profile/**, ${server.servlet.context-path}/api/address/**, ${server.servlet.context-path}/api/fashion-e-commerce-profile-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-profile-backlist
          uri: lb://FASHION-E-COMMERCE-PROFILE-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/admin/profile/**, ${server.servlet.context-path}/api/admin/address/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: authentication-service-order-whitelist
          uri: lb://FASHION-E-COMMERCE-ORDER-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/order-service/**, ${server.servlet.context-path}/api/order/**, ${server.servlet.context-path}/api/fashion-e-commerce-order-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-order-backlist
          uri: lb://FASHION-E-COMMERCE-ORDER-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/admin/order/**
          filters:
            - StripPrefix=1
            - name: Authentication

        - id: authentication-service-payment-whitelist
          uri: lb://FASHION-E-COMMERCE-PAYMENT-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/payment-service/**, ${server.servlet.context-path}/api/payment/**, ${server.servlet.context-path}/api/fashion-e-commerce-payment-service/**
          filters:
            - StripPrefix=1

        - id: authentication-service-payment-backlist
          uri: lb://FASHION-E-COMMERCE-PAYMENT-SERVICE
          predicates:
            - Path=${server.servlet.context-path}/api/admin/payment/**
          filters:
            - StripPrefix=1
            - name: Authentication
