server:
  servlet:
    context-path: /api
  port: 8003

spring:
  application:
    name: fashion-e-commerce-product-service

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    topic:
      create-variant: create-variant
      update-variant: update-variant
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: "data_variant_product:com.lamnguyen.product_service.event.DataVariantEvent"

  data:
    mongodb:
      uri: mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}/${spring.data.mongodb.database}
      database: ${MONGO_DATABASE:fashion-e-commerce}
      auto-index-creation: true

application:
  white-list:
    - /${spring.application.name}/actuator/**
    - /product-service/greeting
    - /collection/v1/**
    - /product/v1/**

grpc:
  server:
    port: 8103
  client:
    fashion-e-commerce-media-service:
      enableKeepAlive: true
      negotiationType: plaintext
    fashion-e-commerce-inventory-service:
      enableKeepAlive: true
      negotiationType: plaintext
    fashion-e-commerce-file-search-service:
      enableKeepAlive: true
      negotiationType: plaintext

