server:
  servlet:
    context-path: /api
  port: 8006

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    topic:
      create-cart: create-cart
      delete-cart-items: delete-cart-items
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              # mapping: "info_address_shipping:com.lamnguyen.profile_service.message.InfoAddressShipping"
    consumer:
      group-id: cart
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "create_cart"
            type:
              mapping: "create_cart:com.lamnguyen.cart_service.message.CreateCartMessage,delete_cart_items:com.lamnguyen.cart_service.message.DeleteCartItemsMessage"
  application:
    name: fashion-e-commerce-cart-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: ${application.database}
    url: ${spring.datasource.url}
    locations: classpath:db/migration
  jackson:
    mapper:
      sort-properties-alphabetically: false

application:
  white-list:
    - /cart-service/greeting
    
grpc:
  server:
    port: ${GRPC_PORT:8106}
  client:
    fashion-e-commerce-product-service:
      enableKeepAlive: true
      negotiationType: plaintext
    fashion-e-commerce-inventory-service:
      enableKeepAlive: true
      negotiationType: plaintext
