spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${application.database}
    username: "{cipher}f980b526fbe733750379bd010aa75cbd69b76e0716f79eafcff92d4c781c3eaf"
    password: "{cipher}67009e12bd4aae08943615816c32334b10197a19c724440bce2dfec55f49bb84"
    driver-class-name: ${MYSQL_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari:
      auto-commit: ${MYSQL_AUT_COMMIT:on}
      maximum-pool-size: ${MYSQL_MAXIMUM_POOL_SIZE:8}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      database: ${REDIS_DATABASE:13}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:60000}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:60000}
      lettuce:
        pool:
          max-active: ${REDIS_MAX_POOL_ACTIVE:8}
          max-idle: ${REDIS_MAX_POOL_IDLE:8}
          min-idle: ${REDIS_MIN_POOL_IDLE:0}
          max-wait: ${REDIS_MAX_POOL_WAIT:-1}

application:
  admin:
    email: "{cipher}5162c870a1a56d735a282344df2e1e2fde2a9884c38a9ff8796c42e0722dc515274c2d88f7f498b8a994d68e8a9d92ac"
    password: "{cipher}10566c1f4fbfef942b8ac55f36a32b8e8c2c0f91380ae878fe1aee17d003fd2c"
  database: ${MYSQL_DATABASE:authentication_fashion_e_commerce}
  BCrypt-length: ${BCRYPT_LENGTH:16}
  jwt:
    iss: ${JWT_ISS:https://kimi-fashion-e-commerce.com}
    secret-key: "{cipher}56d35a61253e7f710dceceb07613f06449784764fc4611ed11da947b82e56578a772ebe6c720a90922b1b4df507da1a8602c2901d320323c773a3abfabc82837"
    claim: ${JWT_CLAIM:payload}

logging:
  level:
    org.springframework.security: trace