server:
  servlet:
    context-path: /api
  port: 8004


spring:
  application:
    name: fashion-e-commerce-media-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #      properties:
  #        spring:
  #          json:
  #            trusted:
  #              packages: "send_mail_verify"
  #            type:
  #              mapping: "send_mail_verify:com.lamnguyen.notification_service.message.SendMailVerifyMessage"

  data:
    mongodb:
      uri: ${MONGO_PROTO:mongodb+srv}://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}/${spring.data.mongodb.database}
      database: ${MONGO_DATABASE:media-fashion-e-commerce}
      auto-index-creation: true

application:
  white-list:
    - /${spring.application.name}/actuator/**
    - /media-service/greeting
    - /resource/images/**
  path-file-manager: ${PATH_FILE_MANAGE:/home/user/Downloads/resources}

grpc:
  server:
    port: 8104
