spring:
  data:
    mongodb:
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}/${spring.data.mongodb.database}
      database: ${MONGO_DATABASE:media-fashion-e-commerce}
      auto-index-creation: true
