spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${application.database}
    username: '{cipher}2253f048e4e6dc59b6b1a5cef9189c133f9f5e431cd0a0b5dd36ada3c55a763c'
    password: "'{cipher}fdc9f0e97762a54078102cee96ecc9ea84347faa2e31cd466ef888ac271b621b'"
    driver-class-name: ${MYSQL_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari:
      auto-commit: ${MYSQL_AUT_COMMIT:on}
      maximum-pool-size: ${MYSQL_MAXIMUM_POOL_SIZE:8}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      database: ${REDIS_DATABASE:10}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:60000}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:60000}
      lettuce:
        pool:
          max-active: ${REDIS_MAX_POOL_ACTIVE:8}
          max-idle: ${REDIS_MAX_POOL_IDLE:8}
          min-idle: ${REDIS_MIN_POOL_IDLE:0}
          max-wait: ${REDIS_MAX_POOL_WAIT:-1}


application:
  database: ${MYSQL_DATABASE:profile_fashion_e_commerce}
  BCrypt-length: ${BCRYPT_LENGTH:16}
  jwt:
    iss: ${JWT_ISS:https://kimi-fashion-e-commerce.com}
    secret-key: "{cipher}ae3e002e1f4cae051e8a957764d6d9eb8780f954faef17f53b8efc22fe2684434cb22d4a4459ea263a80f880ae14374979a2ad128049b85f58f9ab724f41b222"
    claim: ${JWT_CLAIM:payload}

logging:
  level:
    org.springframework.security: trace